// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/meals": {
    params: {};
  };
  "/meals/add": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/meals" | "/meals/add" | "/login" | "/register" | "/*";
  };
  "./components/view-meals/View.jsx": {
    id: "components/view-meals/View";
    page: "/meals" | "/meals/add";
  };
  "./components/add-meal/Meal.jsx": {
    id: "components/add-meal/Meal";
    page: "/meals/add";
  };
  "./components/identity/Login.jsx": {
    id: "components/identity/Login";
    page: "/login";
  };
  "./components/identity/Register.jsx": {
    id: "components/identity/Register";
    page: "/register";
  };
  "./catchall.jsx": {
    id: "catchall";
    page: "/" | "/*";
  };
};