// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/meals/add": {
    params: {};
  };
  "/meals/view": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/meals/add" | "/meals/view" | "/*";
  };
  "./components/Meal.jsx": {
    id: "components/Meal";
    page: "/meals/add";
  };
  "./components/View.jsx": {
    id: "components/View";
    page: "/meals/view";
  };
  "catchall.jsx": {
    id: "catchall";
    page: "/" | "/*";
  };
};