CREATE TABLE IF NOT EXISTS items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  meal_id INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  notes VARCHAR(255) DEFAULT NULL,
  gluten BOOLEAN NOT NULL DEFAULT FALSE,
  dairy BOOLEAN NOT NULL DEFAULT FALSE,
  red_meat BOOLEAN NOT NULL DEFAULT FALSE,
  alcohol BOOLEAN NOT NULL DEFAULT FALSE,
  caffeine BOOLEAN NOT NULL DEFAULT FALSE,
  FOREIGN KEY (meal_id) REFERENCES meals(id) ON DELETE CASCADE,
  INDEX idx_meal_id (meal_id)
)